//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class cd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cd()
        {
            this.cd_esittaja = new HashSet<cd_esittaja>();
            this.cd_kappale = new HashSet<cd_kappale>();
        }
    
        public int avain { get; set; }
        public string nimi { get; set; }
        public Nullable<int> yhtio_avain { get; set; }
        public int vuosi_avain { get; set; }
        public string kuvapath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cd_esittaja> cd_esittaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cd_kappale> cd_kappale { get; set; }
        public virtual vuosi vuosi { get; set; }
        public virtual yhtio yhtio { get; set; }
    }
}
