//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class cd_kappale
    {
        public int avain { get; set; }
        public int cd_avain { get; set; }
        public int kappale_avain { get; set; }
    
        public virtual cd cd { get; set; }
        public virtual kappale kappale { get; set; }
    }
}
