//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class esittaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public esittaja()
        {
            this.cd_esittaja = new HashSet<cd_esittaja>();
            this.kappales = new HashSet<kappale>();
        }
    
        public int avain { get; set; }
        public string nimi { get; set; }
        public int maa_avain { get; set; }
        public int vuosi_avain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cd_esittaja> cd_esittaja { get; set; }
        public virtual maa maa { get; set; }
        public virtual vuosi vuosi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kappale> kappales { get; set; }
    }
}
