//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class kappale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kappale()
        {
            this.cd_kappale = new HashSet<cd_kappale>();
            this.kappale_genre = new HashSet<kappale_genre>();
        }
    
        public int avain { get; set; }
        public string nimi { get; set; }
        public int kesto { get; set; }
        public int esittaja_avain { get; set; }
        public int vuosi_avain { get; set; }
        public string tubepath { get; set; }
        public Nullable<int> numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cd_kappale> cd_kappale { get; set; }
        public virtual esittaja esittaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kappale_genre> kappale_genre { get; set; }
        public virtual vuosi vuosi { get; set; }
    }
}
