//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class kappale_genre
    {
        public int avain { get; set; }
        public Nullable<int> kappale_avain { get; set; }
        public Nullable<int> genre_avain { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual kappale kappale { get; set; }
    }
}
